---
title: "Data Visualization: Lapse to Smoking Datasets"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=0.7in
header-includes:
   - \usepackage{float}
output:
  pdf_document: 
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r}
library(knitr)
library(xtable)
library(dplyr)
library(ggplot2)
library(gridExtra)
path.output_data <- Sys.getenv("path.output_data")
```

```{r}
df.breakfree.01 <- read.csv(file.path(path.output_data, "BreakFree/df.analysis.01.csv"))
df.breakfree.02a <- read.csv(file.path(path.output_data, "BreakFree/df.analysis.02a.csv"))
df.breakfree.02b <- read.csv(file.path(path.output_data, "BreakFree/df.analysis.02b.csv"))
df.breakfree.03 <- read.csv(file.path(path.output_data, "BreakFree/df.analysis.03.csv"))
df.breakfree.04a <- read.csv(file.path(path.output_data, "BreakFree/df.analysis.04a.csv"))
df.breakfree.04b <- read.csv(file.path(path.output_data, "BreakFree/df.analysis.04b.csv"))
df.pns.01 <- read.csv(file.path(path.output_data, "PNS/df.analysis.01.csv"))
df.pns.02a <- read.csv(file.path(path.output_data, "PNS/df.analysis.02a.csv"))
df.pns.02b <- read.csv(file.path(path.output_data, "PNS/df.analysis.02b.csv"))

list.all.df <- list(df.breakfree.01 = df.breakfree.01, df.breakfree.02a = df.breakfree.02a, df.breakfree.02b = df.breakfree.02b,
                    df.breakfree.03 = df.breakfree.03, df.breakfree.04a = df.breakfree.04a, df.breakfree.04b = df.breakfree.04b,
                    df.pns.01 = df.pns.01, df.pns.02a = df.pns.02a, df.pns.02b = df.pns.02b)
```

```{r}
# Specify parameters
tot.days.breakfree <- 10
tot.days.pns <- 21
```

```{r}
# Functions to create plot.od and assign colors to time intervals
CreatePlotID <- function(df){
  nobs.by.id <- df %>% group_by(id) %>% summarise(n())
  df$plot.id <- rep(1:nrow(nobs.by.id), nobs.by.id$`n()`)
  return(df)
}

CreateIntervalColors <- function(df){
  # YES: red, UNKNOWN: orange, NO: blue
  df <- df %>% mutate(colors.smoking.label=if_else(smoking.label=="YES", "#D55E00", if_else(smoking.label=="NO", "#56B4E9", "#999999")))
  return(df)
}

for(i in 1:length(list.all.df)){
  this.df <- list.all.df[[i]] %>% CreatePlotID(.) %>% CreateIntervalColors(.)
  list.all.df[[i]] <- this.df
}

df.breakfree.01 <- list.all.df$df.breakfree.01
df.breakfree.02a <- list.all.df$df.breakfree.02a
df.breakfree.02b <- list.all.df$df.breakfree.02b

df.breakfree.03 <- list.all.df$df.breakfree.03
df.breakfree.04a <- list.all.df$df.breakfree.04a
df.breakfree.04b <- list.all.df$df.breakfree.04b

df.pns.01 <- list.all.df$df.pns.01
df.pns.02a <- list.all.df$df.pns.02a
df.pns.02b <- list.all.df$df.pns.02b
```

```{r}
# Function for plotting
PlotIntervals <- function(df, tot.days, title.string){
  
  gg <- df %>% group_by(id) %>%
  ggplot(aes(LB.seconds, num.cigs.smoked)) + geom_segment(aes(x = LB.seconds, y = plot.id, xend = UB.seconds, yend = plot.id, colour = colors.smoking.label), size=1) + theme(legend.title = element_text(), legend.position = "top") + labs(x = "Day (Ticks at 12AM)", y = "Each row: one individual", title=title.string) +  scale_x_continuous(breaks = c(0:tot.days)*60*60*24 - 4*60*60, labels = paste(0:tot.days)) + scale_y_continuous(breaks = NULL) + scale_colour_identity(guide = "legend", name ="Label of Time Interval:",labels=c("NO","UNKNOWN","YES"))
  
  return(gg)
}

```

# Break Free Study (EMA Only)

```{r}
gg.breakfree.01 <- PlotIntervals(df = df.breakfree.01, tot.days = tot.days.breakfree, title.string = "Curated Data 01")
gg.breakfree.02a <- PlotIntervals(df = df.breakfree.02a, tot.days = tot.days.breakfree, title.string = "Curated Data 02a")
gg.breakfree.02b <- PlotIntervals(df = df.breakfree.02b, tot.days = tot.days.breakfree, title.string = "Curated Data 02b")
```

```{r, fig.align = 'center', fig.height=10, fig.width=10}
# Place all three plots on the same page
grid.arrange(gg.breakfree.01, gg.breakfree.02a, gg.breakfree.02b, nrow=3, heights = c(2.2,2,2),
             top="Break Free Self-Reported Lapse to Smoking (All EMA Types)")
```

# Break Free Study (EMA and Puffmarker)

```{r}
gg.breakfree.03 <- PlotIntervals(df = df.breakfree.03, tot.days = tot.days.breakfree, title.string = "Curated Data 03")
gg.breakfree.04a <- PlotIntervals(df = df.breakfree.04a, tot.days = tot.days.breakfree, title.string = "Curated Data 04a")
gg.breakfree.04b <- PlotIntervals(df = df.breakfree.04b, tot.days = tot.days.breakfree, title.string = "Curated Data 04b")
```

```{r, fig.align = 'center', fig.height=10, fig.width=10}
# Place all three plots on the same page
grid.arrange(gg.breakfree.03, gg.breakfree.04a, gg.breakfree.04b, nrow=3, heights = c(2.2,2,2),
             top="Break Free Self-Reported Lapse to Smoking (All EMA Types and Puffmarker)")
```

# PNS Study

```{r}
gg.pns.01 <- PlotIntervals(df = df.pns.01, tot.days = tot.days.pns, title.string = "Curated Data 01")
gg.pns.02a <- PlotIntervals(df = df.pns.02a, tot.days = tot.days.pns, title.string = "Curated Data 02a")
gg.pns.02b <- PlotIntervals(df = df.pns.02b, tot.days = tot.days.pns, title.string = "Curated Data 02b")
```


```{r, fig.align = 'center', fig.height=10, fig.width=10}
# Place all three plots on the same page
grid.arrange(gg.pns.01, gg.pns.02a, gg.pns.02b, nrow=3, heights = c(2.2,2,2),
             top="PNS Self-Reported Lapse to Smoking (All EMA Types)")
```
